// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvzv9bLIw1oBjKcLpRi4B_N_DkIDQlKho',
    appId: '1:675290864991:web:809a3ca6ae70e826efaaea',
    messagingSenderId: '675290864991',
    projectId: 'nawelapp-eeec3',
    authDomain: 'nawelapp-eeec3.firebaseapp.com',
    storageBucket: 'nawelapp-eeec3.firebasestorage.app',
    measurementId: 'G-6555HTL751',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvytjnxv4wDzkD7_BJiTFhpbyRkDZf46Y',
    appId: '1:675290864991:android:a36113e9ab946788efaaea',
    messagingSenderId: '675290864991',
    projectId: 'nawelapp-eeec3',
    storageBucket: 'nawelapp-eeec3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOCN3gFY3S64BRYGV5Z2s4Y0c2q-cxe4s',
    appId: '1:675290864991:ios:6f312b7c3630ae75efaaea',
    messagingSenderId: '675290864991',
    projectId: 'nawelapp-eeec3',
    storageBucket: 'nawelapp-eeec3.firebasestorage.app',
    iosBundleId: 'com.example.nawel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOCN3gFY3S64BRYGV5Z2s4Y0c2q-cxe4s',
    appId: '1:675290864991:ios:6f312b7c3630ae75efaaea',
    messagingSenderId: '675290864991',
    projectId: 'nawelapp-eeec3',
    storageBucket: 'nawelapp-eeec3.firebasestorage.app',
    iosBundleId: 'com.example.nawel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvzv9bLIw1oBjKcLpRi4B_N_DkIDQlKho',
    appId: '1:675290864991:web:3e64563e62667367efaaea',
    messagingSenderId: '675290864991',
    projectId: 'nawelapp-eeec3',
    authDomain: 'nawelapp-eeec3.firebaseapp.com',
    storageBucket: 'nawelapp-eeec3.firebasestorage.app',
    measurementId: 'G-MYEVKCQN75',
  );
}
